---
name: Initialize the environment for building Ansible docs
description: Sets up various requirements and preparation for building Ansible docs. Requires Python.
inputs:
  dest-dir:
    description: The destination directory for preparing the build environment. Note that this must be within the Workspace for hashes to be calculated.
    required: false
    default: ${{ runner.temp }}/docsbuild
  collections:
    description: |
      Limit the docs build to one or more collections, in the form namespace.collection.
      Multiple collections should be separated by spaces.
      If this isn't limited, then all collections in the collections path will be included in the built docs.
    required: false
  skip-init:
    description: |
      If 'true', dest-dir will be assumed to already be initialized, so this action will only install
      antsibull-docs and the contents of the requirements.txt file in dest-dir.
    required: false
    default: 'false'
  fail-on-error:
    description: |
      Corresponds to the --fail-on-error flag in antsibull-docs. Fails if plugins cannot be parsed.
      Has no effect if skip-init is true.
    required: false
    default: 'false'
  lenient:
    description: |
      Corresponds to the --lenient flag for antsibull-docs sphinx-init.
      By default, the build process will fail on warnings unless this is set to 'true'.
      Has no effect if skip-init is true.
    required: false
    default: 'false'
  antsibull-docs-version:
    description: |
      The version of antsibull-docs to install. When set, it refers to a git ref from which to install.
      If not set, the latest version from PyPI is installed.
    required: false
  antsibull-docs-repository:
    description: |
      When antsibull-docs-version is specified, this is the GitHub repository to which antsibull-docs-version refers.
      Has no effect if antsibull-docs-version is not supplied.
    default: ansible-community/antsibull-docs
    required: false
  provide-link-targets:
    description: A newline separated list of link targets that should not cause reference errors. A small RST file will be created during the build which contains these labels.
    required: false
    type: string
  intersphinx-links:
    description: |
      A newline separated list of entries to add to the intersphinx_mapping in the generated conf.py.
      Use the syntax `identifier:https://server/path` to add the identifier `identifier` with URL
      `https://server/path`.
    required: false
    type: string
  squash-hierarchy:
    description: |
      If 'true', the collection documentation will be created at top-level and not in a subdirectory `namespace/collection_name/`.
      This is only possible if 'collections' contains exactly one collection.
    required: false
    default: 'false'
  index-rst-source:
    description: |
      Copy the provided file to `rst/index.rst` intead of templating a default one.
    required: false
  project:
    description: |
      Sets the `project` value in the Sphinx configuration.
    required: false
  copyright:
    description: |
      Sets the `copyright` value in the Sphinx configuration.
    required: false
  title:
    description: |
      Sets the `title` and `html_short_title` values in the Sphinx configuration.
      If `html-short-title` is also specified, only `title` will be set to the value
      specified here.
    required: false
  html-short-title:
    description: |
      Sets the `html_short_title` value in the Sphinx configuration. If not specified,
      the value of `title` will be used.
    required: false
  extra-conf:
    description: |
      A newline separated list of `key=value` entries that will be added to the generated
      `conf.py`.
    required: false
  extra-html-context:
    description: |
      A newline separated list of `key=value` entries that will be added to the generated
      `conf.py` in `html_context`
    required: false
  extra-html-theme-options:
    description: |
      A newline separated list of `key=value` entries that will be added to the generated
      `conf.py` in `html_theme_options`
    required: false
  append-conf-py:
    description: |
      If provided, this text will be appended to the generated `conf.py` as-is.
    required: false
outputs:
  build-script:
    description: The path of the build script to execute.
    value: ${{ steps.init.outputs.build-script }}
  build-html:
    description: The path of the build's html output directory.
    value: ${{ steps.init.outputs.build-html }}

runs:
  using: composite
  steps:
    - name: Install antsibull-docs and Initialize Sphinx
      id: init
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: '1'
        _INPUT_ANTSIBULL_DOCS_VERSION: ${{ inputs.antsibull-docs-version }}
        _INPUT_ANTSIBULL_DOCS_REPO: ${{ inputs.antsibull-docs-repository }}
        _INPUT_COLLECTIONS: ${{ inputs.collections }}
        _INPUT_DEST_DIR: ${{ inputs.dest-dir }}
        _INPUT_SKIP_INIT: ${{ inputs.skip-init }}
        _INPUT_PROVIDE_LINK_TARGETS: ${{ inputs.provide-link-targets }}
        _INPUT_INTERSPHINX_LINKS: ${{ inputs.intersphinx-links }}
        _INPUT_PROJECT: ${{ inputs.project }}
        _INPUT_COPYRIGHT: ${{ inputs.copyright }}
        _INPUT_TITLE: ${{ inputs.title }}
        _INPUT_HTML_SHORT_TITLE: ${{ inputs.html-short-title }}
        _INPUT_EXTRA_CONF: ${{ inputs.extra-conf }}
        _INPUT_EXTRA_HTML_CONTEXT: ${{ inputs.extra-html-context }}
        _INPUT_EXTRA_HTML_THEME_OPTIONS: ${{ inputs.extra-html-theme-options }}
        _INPUT_APPEND_CONF_PY: ${{ inputs.append-conf-py }}
      shell: bash
      run: |
        echo "::group::Installing antsibull-docs"
        if [[ "${_INPUT_ANTSIBULL_DOCS_VERSION}" != "" ]] ; then
            pip install "https://github.com/${_INPUT_ANTSIBULL_DOCS_REPO}/archive/${_INPUT_ANTSIBULL_DOCS_VERSION}.tar.gz" sphinx_ansible_theme
        else
            pip install antsibull-docs sphinx_ansible_theme
        fi
        antsibull-docs --version
        echo "::endgroup::"

        if [[ "${_INPUT_SKIP_INIT}" != "true" ]] ; then
            echo "::group::Create destination directory"
            mkdir -p "${_INPUT_DEST_DIR}"
            echo "::endgroup::"

            INIT_ARGS=()

            if [[ "${_INPUT_INTERSPHINX_LINKS}" != "" ]]; then
                echo "::group::Building list of intersphinx links"
                _INTERSPHINX_ARGS=()
                while read -r line; do
                    if [ "${line}" != "" ]; then
                        _INTERSPHINX_ARGS+=("--intersphinx" "${line}")
                    fi
                done <<< "${_INPUT_INTERSPHINX_LINKS}"
                echo "Intersphinx args: ${_INTERSPHINX_ARGS[@]@Q}"
                echo "::endgroup::"
                INIT_ARGS+=("${_INTERSPHINX_ARGS[@]}")
            fi

            if [[ "${_INPUT_EXTRA_CONF}" != "" ]]; then
                echo "::group::Building list of extra configuration entries"
                _EXTRA_CONF=()
                while read -r line; do
                    if [ "${line}" != "" ]; then
                        _EXTRA_CONF+=("--extra-conf" "${line}")
                    fi
                done <<< "${_INPUT_EXTRA_CONF}"
                echo "Extra configuration entries: ${_EXTRA_CONF[@]@Q}"
                echo "::endgroup::"
                INIT_ARGS+=("${_EXTRA_CONF[@]}")
            fi

            if [[ "${_INPUT_EXTRA_HTML_CONTEXT}" != "" ]]; then
                echo "::group::Building list of extra HTML configuration entries"
                _EXTRA_HTML_CONTEXT=()
                while read -r line; do
                    if [ "${line}" != "" ]; then
                        _EXTRA_HTML_CONTEXT+=("--extra-html-context" "${line}")
                    fi
                done <<< "${_INPUT_EXTRA_HTML_CONTEXT}"
                echo "Extra HTML context entries: ${_EXTRA_HTML_CONTEXT[@]@Q}"
                echo "::endgroup::"
                INIT_ARGS+=("${_EXTRA_HTML_CONTEXT[@]}")
            fi

            if [[ "${_INPUT_EXTRA_HTML_THEME_OPTIONS}" != "" ]]; then
                echo "::group::Building list of extra HTML theme options"
                _EXTRA_HTML_THEME_OPTIONS=()
                while read -r line; do
                    if [ "${line}" != "" ]; then
                        _EXTRA_HTML_THEME_OPTIONS+=("--extra-html-theme-options" "${line}")
                    fi
                done <<< "${_INPUT_EXTRA_HTML_THEME_OPTIONS}"
                echo "Extra HTML theme option entries: ${_EXTRA_HTML_THEME_OPTIONS[@]@Q}"
                echo "::endgroup::"
                INIT_ARGS+=("${_EXTRA_HTML_THEME_OPTIONS[@]}")
            fi

            INIT_ARGS+=("--use-current")
            ${{ fromJSON(inputs.fail-on-error) && 'INIT_ARGS+=("--fail-on-error")' || '' }}
            ${{ fromJSON(inputs.lenient) && 'INIT_ARGS+=("--lenient")' || '' }}
            ${{ fromJSON(inputs.squash-hierarchy) && 'INIT_ARGS+=("--squash-hierarchy")' || '' }}
            INIT_ARGS+=("--dest-dir" "${_INPUT_DEST_DIR}")
            ${{ inputs.index-rst-source && format('INIT_ARGS+=("--index-rst-source" "{0}")', inputs.index-rst-source) || '' }}
            ${{ inputs.project && 'INIT_ARGS+=("--project" "${_INPUT_PROJECT}")' || '' }}
            ${{ inputs.copyright && 'INIT_ARGS+=("--copyright" "${_INPUT_COPYRIGHT}")' || '' }}
            ${{ inputs.title && 'INIT_ARGS+=("--title" "${_INPUT_TITLE}")' || '' }}
            ${{ inputs.html-short-title && 'INIT_ARGS+=("--html-short-title" "${_INPUT_HTML_SHORT_TITLE}")' || '' }}

            echo "::group::Initialize Sphinx"
            echo "Run antsibull-docs sphinx-init ${INIT_ARGS[@]@Q} ${_INPUT_COLLECTIONS}"
            antsibull-docs sphinx-init "${INIT_ARGS[@]}" ${_INPUT_COLLECTIONS}
            echo "::endgroup::"
        fi

        if [[ "${_INPUT_PROVIDE_LINK_TARGETS}" != "" ]]; then
            echo "::group::Create small RST file for link"
            mkdir -p "${_INPUT_DEST_DIR}/rst"
            echo ":orphan:" > "${_INPUT_DEST_DIR}/rst/_targets.rst"
            echo "" >> "${_INPUT_DEST_DIR}/rst/_targets.rst"
            while read -r line; do
              if [ "${line}" != "" ]; then
                echo ".. _${line}:" >> "${_INPUT_DEST_DIR}/rst/_targets.rst"
              fi
            done <<< "${_INPUT_PROVIDE_LINK_TARGETS}"
            echo "" >> "${_INPUT_DEST_DIR}/rst/_targets.rst"
            echo "Replacement stub for existing reference" >> "${_INPUT_DEST_DIR}/rst/_targets.rst"
            echo "=======================================" >> "${_INPUT_DEST_DIR}/rst/_targets.rst"
            echo "" >> "${_INPUT_DEST_DIR}/rst/_targets.rst"
            echo "This file just exists to provide link targets. Please ignore it." >> "${_INPUT_DEST_DIR}/rst/_targets.rst"
            echo "Content of ${_INPUT_DEST_DIR}/rst/_targets.rst:"
            echo ""
            cat "${_INPUT_DEST_DIR}/rst/_targets.rst"
            echo "::endgroup::"
        fi

        if [[ "${_INPUT_APPEND_CONF_PY}" != "" ]]; then
            echo "::group::Appending to conf.py"
            echo "${_INPUT_APPEND_CONF_PY}" >> "${_INPUT_DEST_DIR}/conf.py"
            echo "Content of ${_INPUT_DEST_DIR}/conf.py:"
            echo ""
            cat "${_INPUT_DEST_DIR}/conf.py"
            echo "::endgroup::"
        fi

        echo "::group::Install additional requirements"
        pip install -r "${_INPUT_DEST_DIR}/requirements.txt"
        echo "::endgroup::"

        echo "build-script=${_INPUT_DEST_DIR}/build.sh" >> ${GITHUB_OUTPUT}
        echo "build-html=${_INPUT_DEST_DIR}/build/html" >> ${GITHUB_OUTPUT}
