---
name: Ansible collection docs - publish to GitHub Pages
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The build artifact that contains the rendered HTML. Required when action == 'publish'
        required: false
        type: string
      destination-dir:
        description: |
          The destination path within the published site. Should not start with a forward slash '/'.
          If not given, the destination will be calculated based on what triggered the event.
        required: false
        type: string

    #   surge-site-name:
    #     description: The full surge site domain to publish or teardown.
    #     required: true
    #     type: string
      action:
        description: Action to perform. 'publish' to publish the site, 'teardown' to tear it down.
        required: false
        default: 'publish'
        type: string
      base-url:
        description: |
          The base URL of the published site, ending with a forward slash '/'.'
          This is not used for the publishing process, but the resulting destination dir will be concatenated to it,
          and then returned in the workflow's outputs.
        required: false
        type: string
        default: ''
    outputs:
      url:
        description: The destination path. If base-url was provided, it will be pre-pended.
        value: ${{ jobs.publish-gh-pages.outputs.url }}
    secrets:
      GH_TOKEN:
        description: |
          The token used for publishing to GitHub Pages.
          Even when using the workflow secret, it must be passed explicitly.
        required: true
jobs:
  publish-gh-pages:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      url: ${{ steps.vars.outputs.url }}
    steps:
      - name: Process variables
        id: vars
        uses: actions/github-script@v6
        with:
          script: |
            const inputs = ${{ toJSON(inputs) }}
            var destination_dir = inputs['destination-dir']
            var base_url = inputs['base-url']

            if (destination_dir == '') {
                const gh = ${{ toJSON(github) }}

                if (gh['event_name'] == 'pull_request') {
                    destination_dir = `pr/${gh['event']['number']}`
                }
                else {
                    destination_dir = `${gh['ref_type']}/${gh['ref_name']}`
                }
            }

            core.setOutput('dest', destination_dir)
            core.setOutput('url', `${base_url}/${destination_dir}`)

      - name: Check required
        if: inputs.action == 'publish' && inputs.artifact-name == ''
        run: |
          echo "::error title=Missing artifact-name::action was 'publish' but artifact-name was not supplied."
          exit 1

      - name: Retrieve rendered docs
        if: inputs.action == 'publish'
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: html

      - name: Teardown
        if: inputs.action == 'teardown'
        run: mkdir -p html

      - name: Publish
        # if: inputs.action == 'publish'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: html
          destination-dir: ${{ steps.vars.outputs.dest }}
