---
name: Generate Wiki Docs
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/_shared*
      - .github/workflows/generate-wiki-docs.yml
      - .internal/ansible/**
      - actions/**/action.yml

env:
  # if you want this workflow to run on your fork, you must:
  # 1) enable the wiki (and have at minimum a main/default page)
  # 2) set the GENERATE_WIKI_PAGES secret in your fork to the value "yes"
  SHOULD_RUN: ${{ secrets.GENERATE_WIKI_PAGES == 'yes' || github.repository == 'ansible-community/github-docs-build' }}

jobs:
  generate:
    env:
      WIKI: ${{ github.workspace }}/wiki
      ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/.internal/ansible
    runs-on: ubuntu-latest
    steps:
      - if: fromJSON(env.SHOULD_RUN)
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Checkout wiki
        if: fromJSON(env.SHOULD_RUN)
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}.wiki
          path: ${{ env.WIKI }}
          persist-credentials: false

      - uses: actions/setup-python@v6
        if: fromJSON(env.SHOULD_RUN)
        with:
          python-version: '3.13'

      - name: Install Ansible
        if: fromJSON(env.SHOULD_RUN)
        run: pip install 'ansible-core>=2.15,<2.16' --disable-pip-version-check

      - name: Generate new docs
        if: fromJSON(env.SHOULD_RUN)
        run: >-
          ansible-playbook
          internal.gha_docs.generate_docs
          -e "action_output_dir=$WIKI/actions"
          -e "workflow_output_dir=$WIKI/workflows"

      - name: Publish docs
        if: fromJSON(env.SHOULD_RUN)
        uses: Andrew-Chen-Wang/github-wiki-action@50650fccf3a10f741995523cf9708c53cec8912a # v4.4.0
        with:
          path: ${{ env.WIKI }}
          commit-message: 'Docs for ${{ github.repository }}/${{ github.event.head_commit.id }} : ${{ github.event.head_commit.message }}'
