---
name: test - action/build-html
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/test-action-build-html.yml
      - actions/ansibe-docs-build-html/**
  pull_request:
    paths:
      - .github/workflows/test-action-build-html.yml
      - actions/ansibe-docs-build-html/**

jobs:
  tests:
    name: Simple tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Simple invoke - no copy, no artifact
        id: simple1
        uses: ./actions/ansible-docs-build-html
        with:
          build-script: .test/simple-build/build.sh
          build-html: .test/simple-build/html
          artifact-upload: false

      - name: Download artifacts
        uses: actions/download-artifact@v2
        id: simple1-artifact
        with:
          path: .artifacts/simple1

      - name: assert
        shell: python
        run: |
          expected_hash = r'${{ hashFiles('.test/simple-build/src') }}'
          output_hash = r'${{ steps.simple1.outputs.hash }}'
          output_build_html = r'${{ steps.simple1.outputs.build-html }}'
          artifact_hash = r'${{ hashFiles(steps.simple1-artifact.outputs.download-path) }}'

          assert output_build_html == '.test/simple-build/html'
          assert output_hash == expected_hash
          assert artifact_hash != output_hash

      - name: Simple invoke - with copy, no artifact
        id: simple2
        uses: ./actions/ansible-docs-build-html
        with:
          build-script: .test/simple-build/build.sh
          build-html: .test/simple-build/html
          copy-build: .copies/simple2/html
          artifact-upload: false

      - name: Download artifacts
        uses: actions/download-artifact@v2
        id: simple2-artifact
        with:
          path: .artifacts/simple1

      - name: assert
        shell: python
        run: |
          expected_hash = r'${{ hashFiles('.test/simple-build/src') }}'
          output_hash = r'${{ steps.simple2.outputs.hash }}'
          output_build_html = r'${{ steps.simple2.outputs.build-html }}'
          artifact_hash = r'${{ hashFiles(steps.simple2-artifact.outputs.download-path) }}'
          original_build_hash = r'${{ hashFiles('.test/simple-build/html') }}'

          assert output_build_html == '.copies/simple2/html'
          assert output_hash == expected_hash
          assert output_hash == original_build_hash
          assert artifact_hash != output_hash
